import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import { prisma } from '../lib/prisma';
import { useGetData } from '../hooks/useRequest';
import ActivityForm from '../components/form/activities/activityForm';
import UserSimpleForm from '../components/form/users/userSimpleForm';

interface IUser
{
  email: string;
  name: string;
  role?: string;
  avatar?: string;
}


export async function getServerSideProps()
{
  const users = await prisma.user.findMany()
  const schedule = await prisma.schedule.findMany()
  const activity = await prisma.areaActivity.findMany()
  return{
    props:{
      schedule: JSON.parse(JSON.stringify(schedule)),
      users: JSON.parse(JSON.stringify(users)),
      activity: JSON.parse(JSON.stringify(activity)),
    }
  }
}


export default function Home(props:any)
{
  const [agendas, setAgenda] = useState(props.schedule)
  const [usuarios, setUser] = useState(props.users)
  const [activity, setActivity] = useState(props.activity)
  const {data: user} = useGetData('api/user')
  const {data: schedule} = useGetData('api/schedule')

  const create = async (data:IUser) => {
    try 
    {
      const response = await fetch('/api/user/create',
      {
        method: 'POST',
        body: JSON.stringify(data),
        headers:{
          'Content-Type': 'application/json'
        }
      })

      if(!response.ok)
      {
        throw new Error(response.statusText);
      }

      return await response.json();
    } 
    catch (error) 
    {
      console.log('Failure')
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Página de integração de funcionalidades
        </h1>

        <p className={styles.description}>
          Listagem e cadastro{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
         
          <a
            href="#"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Agenda</h2>
            <ul>
              {((!schedule || schedule === undefined) &&
                <li>Carregando</li>
              )}
              { (schedule && schedule !== undefined) &&
                schedule.map((agenda:any) =>(
                  <li key={agenda.id}>{agenda.day}</li>
                ))
              }
            </ul>
          </a>

          <div className={styles.card}>
            <h2>Áreas de atuação</h2>
            <ul>
              {((!activity || activity === undefined) &&
                <li>Carregando</li>
              )}
              { (activity && activity !== undefined) &&
                activity.map((activity:any) =>(
                  <li key={activity.id}>Nome: {activity.name} | Cor: {activity.color}</li>
                ))
              }
            </ul>
            <ActivityForm url='api/activity/create' type='POST'/>
          </div>

          <div className={styles.card}>
            <h2>usuários</h2>
            <ul>
              {((!user || user === undefined) &&
                <li>Carregando</li>
              )}
              { (user && user !== undefined) &&
                user.map((user:any) => (
                <li key={user.id}>{user.name} - Role: {user.role.toLowerCase()}</li>
              ))}
            </ul>
            <UserSimpleForm url='api/user/create' type='POST'/>
          </div>

          
          

        </div>

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
